name: Build and publish wheels

on:
  push:
    branches:
      - main  # Change this to the main branch name, or use 'master' if that's the default branch.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        os:
          - [ubuntu-20.04, macos-13, macos-14, windows-2019]
        python: ["cp310", "cp311", "cp312"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    # Used to push the built wheels
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: "3.x"
    
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.19.1
      env:
        CIBW_TEST_REQUIRES: pytest numpy
        CIBW_TEST_COMMAND: pytest {project}/tests/test.py
        CIBW_ARCHS_LINUX: auto aarch64
        CIBW_BUILD_FRONTEND: build[uv]
        CIBW_BUILD: cp10* cp11* cp12* cp10*
        CIBW_SKIP: "*-win32 pp*"
      
    - name: Install Twine
      run: python -m pip install twine

    - name: Publish to PyPI
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload wheelhouse/*